# Generated by Django 3.1.7 on 2021-04-01 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=100, verbose_name='product name')),
                ('referral', models.CharField(max_length=100, verbose_name='Referral name')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Middle name')),
                ('dob', models.CharField(max_length=100, verbose_name='Date of Birth')),
                ('mother_name', models.CharField(max_length=100, verbose_name='Nother name')),
                ('relationship', models.CharField(max_length=100, verbose_name='Relationship Status')),
                ('gender', models.CharField(max_length=100, verbose_name='Gender')),
                ('occupation', models.CharField(max_length=100, verbose_name='Occupation')),
                ('ssn', models.CharField(max_length=100, verbose_name='Full SSN')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('state', models.CharField(max_length=100, verbose_name='City/State/Province')),
                ('nationality', models.CharField(max_length=100, verbose_name='Nationality')),
                ('phone', models.CharField(max_length=100, verbose_name='Telephone number')),
                ('fax', models.CharField(max_length=100, verbose_name='Fax number')),
                ('income', models.CharField(max_length=100, verbose_name='Monthly income')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('bank', models.CharField(max_length=100, verbose_name='Financial Institution')),
                ('description', models.CharField(max_length=250, verbose_name="Describe in details how you'll use the money")),
            ],
        ),
    ]
