# Generated by Django 3.1.7 on 2021-04-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='application',
            name='bank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Financial Institution'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Describe in details how you'll use the money"),
        ),
        migrations.AlterField(
            model_name='application',
            name='dob',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='application',
            name='fax',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fax number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='application',
            name='income',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Monthly income'),
        ),
        migrations.AlterField(
            model_name='application',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nother name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nationality'),
        ),
        migrations.AlterField(
            model_name='application',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='application',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telephone number'),
        ),
        migrations.AlterField(
            model_name='application',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='product name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='referral',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referral name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='relationship',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Relationship Status'),
        ),
        migrations.AlterField(
            model_name='application',
            name='ssn',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Full SSN'),
        ),
        migrations.AlterField(
            model_name='application',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City/State/Province'),
        ),
    ]
