# Generated by Django 3.1.7 on 2021-04-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210401_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='back_id',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Back of ID Card'),
        ),
        migrations.AddField(
            model_name='application',
            name='front_id',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Front of ID Card'),
        ),
        migrations.AlterField(
            model_name='application',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mother name'),
        ),
        migrations.AlterField(
            model_name='application',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Prefix'),
        ),
    ]
